### ISSUE TITLE
Optimize styling for mobile devices

### ISSUE THREAD

**Issue by zackshorts** [zackshorts/notes#26]
**Is your feature request related to a problem? Please describe.**
The app is not optimized for mobile devices. There are certain elements that overflow into others.

**Describe the solution you'd like**
Add in a few media queries where needed and adjust the styling. At least do this for the header and main body of text.

**Comment by wcbsmith** [comment]
I addressed these issues in my latest pull request. The header styling works to hide the welcome message and the title. Verified that the body text wraps appropriately.
